global:
  pattern: trivial-pattern
  singleArgoCD: true
  secretLoader:
    disabled: true
main:
  clusterGroupName: prod
  multiSourceConfig:
    enabled: true
    clusterGroupGitRepoUrl: https://github.com/dminnear-rh/clustergroup-chart
    clusterGroupChartGitRevision: disable-vault-role-when-secrets-disabled
